name: Build and Publish Docker Image

on:
  push:
    # Build on all pushes to master
    branches:
      - master
    # And to tagged releases
    tags:
      - 'release-*'
  # Build on demand from the GitHub Actions UI
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:
            - ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
            - ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
